package conflictlog

import "errors"

var (
	ErrManagerNotInitialized        error = errors.New("conflict manager not initialized")
	ErrWriterTimeout                error = errors.New("conflict writer timed out")
	ErrWriterClosed                 error = errors.New("conflict writer closed")
	ErrQueueFull                    error = errors.New("conflict log is full")
	ErrLoggerClosed                 error = errors.New("conflict logger is closed")
	ErrLogWaitAborted               error = errors.New("conflict log handle received abort")
	ErrEmptyRules                   error = errors.New("empty conflict rules")
	ErrUnknownCollection            error = errors.New("unknown collection")
	ErrClosedConnPool               error = errors.New("use of closed connection pool")
	ErrNotMyBucket                  error = errors.New("not my bucket")
	ErrEmptyTarget                  error = errors.New("empty target")
	ErrEmptyScope                   error = errors.New("conflict logging scope should not be empty")
	ErrIncompleteTarget             error = errors.New("one or more of target bucket,scope or collection is empty")
	ErrInvalidLoggingRulesType      error = errors.New("invalid logging rules type")
	ErrInvalidTargetType            error = errors.New("invalid target type")
	ErrInvalidCollectionValueType   error = errors.New("collection value is not string")
	ErrEmptyConflictLoggingMap      error = errors.New("nil or empty conflict logging map not allowed")
	ErrInvalidBucket                error = errors.New("conflict logging bucket not provided or wrong format")
	ErrInvalidCollection            error = errors.New("conflict logging collection not provided or wrong format")
	ErrInvalidCollectionFormat      error = errors.New("conflict logging collection should be in format [scope].[collection]")
	ErrInvalidLoggingRulesFormat    error = errors.New("conflict logging loggingRules should be a json object")
	ErrInvalidLoggingRulesValFormat error = errors.New("conflict logging loggingRules' values should be a json object")
	ErrEmptyBucketEmpty             error = errors.New("conflict logging bucket should not be empty")
	ErrEmptyCollectionEmpty         error = errors.New("conflict logging collection should not be empty")
	ErrNilMapping                   error = errors.New("conflict logging mapping input should not be nil")
	ErrConnPoolGetTimeout           error = errors.New("conflict logging pool get timedout")
	ErrSetMetaTimeout               error = errors.New("conflict logging SetMeta timedout")
)
